-- CMI / 清迈客栈活动状态同步 + 6 月第三周活动发布审计
-- 执行时间：2026-06-17T14:48:58+07:00。
-- 本轮发布素材文件夹：
-- - /Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习
-- - /Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里
-- - /Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子
-- - /Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期
-- - /Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！
-- - /Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇
-- 本轮同步包含：
-- - 归档已结束的 CMI / 清迈客栈已发布活动
-- - 刷新到达 next_check_before 的仍可参加活动
-- - upsert 本轮新增活动，并固定 CLI 上传后的 Supabase Storage 海报 URL

update public.cmi_events
set
  visibility_status = 'archived',
  registration_status = 'closed',
  last_checked_at = '2026-06-17T14:48:58+07:00',
  next_check_before = null,
  raw_source_payload = coalesce(raw_source_payload, '{}'::jsonb) || jsonb_build_object(
    'archivedByAutomationAt', '2026-06-17T14:48:58+07:00',
    'archivedByAutomationReason', '本轮自动化要求归档已结束的 CMI / 清迈客栈活动。'
  ),
  updated_at = timezone('utc'::text, now())
where visibility_status = 'published'
  and (is_cmi_related = true or venue_name = '清迈客栈' or source_type = 'cmi')
  and coalesce(end_at, start_at) < '2026-06-17T14:48:58+07:00'::timestamptz;

update public.cmi_events
set
  last_checked_at = '2026-06-17T14:48:58+07:00',
  next_check_before = case
    when start_at <= ('2026-06-17T14:48:58+07:00'::timestamptz + interval '2 hours') then start_at
    when start_at <= ('2026-06-17T14:48:58+07:00'::timestamptz + interval '48 hours') then start_at - interval '2 hours'
    when start_at is not null then '2026-06-17T14:48:58+07:00'::timestamptz + interval '48 hours'
    else null
  end,
  raw_source_payload = coalesce(raw_source_payload, '{}'::jsonb) || jsonb_build_object(
    'reviewRefreshedByAutomationAt', '2026-06-17T14:48:58+07:00'
  ),
  updated_at = timezone('utc'::text, now())
where visibility_status = 'published'
  and (is_cmi_related = true or venue_name = '清迈客栈' or source_type = 'cmi')
  and (end_at is null or end_at >= '2026-06-17T14:48:58+07:00'::timestamptz)
  and next_check_before is not null
  and next_check_before <= '2026-06-17T14:48:58+07:00'::timestamptz;

insert into public.cmi_events (
  id,
  title,
  event_type,
  start_at,
  end_at,
  recurrence,
  stable_schedule,
  venue_name,
  area,
  latitude,
  longitude,
  price_label,
  registration_label,
  source_type,
  source_label,
  source_url,
  host_name,
  language,
  suitable_for,
  is_cmi_related,
  is_verified,
  verification_status,
  visibility_status,
  last_checked_at,
  next_check_before,
  reliability_note,
  tags,
  summary,
  organizer_name,
  organizer_email,
  contact_email,
  capacity,
  registration_enabled,
  registration_status,
  attendee_visibility,
  cover_image_url,
  detail_body,
  raw_source_payload
)
values
(
  'cmi-machine-learning-intro-2026-06-17',
  '机器学习：从底层逻辑更好地学习和理解 AI',
  'tech',
  '2026-06-17T19:00:00+07:00',
  '2026-06-17T21:00:00+07:00',
  null,
  null,
  '清迈客栈',
  'CMI / 清迈客栈',
  18.7932,
  98.9874,
  '免费参与',
  'CMI Map 一键报名',
  'cmi',
  'CMI 活动宣传内容文件夹',
  null,
  '爱德蒙的东风破 × CMI 社区',
  '中文',
  array['AI 工具使用者', '机器学习初学者', 'Codex / Agent 学习者', '想线下学习讨论的人'],
  true,
  true,
  'verified',
  'published',
  '2026-06-17T14:48:58+07:00',
  '2026-06-17T17:00:00+07:00',
  '信息来自 0617 机器学习推文、发布页、同目录官方海报，并用“0617 灭霸 AI 入门”同时间海报 OCR 交叉核对；时间、地点、费用和参与方式均明确。',
  array['CMI', '清迈客栈', 'AI', '机器学习', '分享会', '免费'],
  '从吴恩达《机器学习》课程开始，理解 AI 背后的基本逻辑、能力边界和学习路径。',
  'CMI 社区',
  'events@cmimap.com',
  null,
  null,
  true,
  'open',
  'count-only',
  'https://sfpcpxlxslnulzlmjcby.supabase.co/storage/v1/object/public/cmi-event-posters/posters/cmi-machine-learning-intro-2026-06-17-1781682307571.png',
  '现在很多人已经开始把 AI 当成日常工具。写文案、做图、写代码、整理资料，AI 好像什么都能帮一点。

但如果只停留在“会用工具”，很容易遇到一个问题：它为什么有时很聪明，有时又会一本正经地胡说？

这周三晚上，爱德蒙的东风破会在清迈客栈带大家从吴恩达课程《机器学习》开始，做一场面向普通学习者的入门分享。

本次会聊：机器学习到底在学习什么；为什么理解机器学习能帮助我们理解 AI；AI 能做什么、不能做什么；普通人如何开始系统学习机器学习。

活动信息：2026 年 6 月 17 日（周三）19:00-21:00，地点清迈客栈，免费参与。原始参与方式为无需报名、直接空降即可；通过 CMI Map 一键报名后，确认邮件会附上微信群、联系人二维码和到场指引。',
  '{
  "sourceFiles": [
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/公众号推文.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/发布页.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/小红书标题.txt",
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/小红书正文.txt",
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/推文.md",
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/机器学习-活动海报-v3.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/机器学习-设计风活动海报-v1.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/机器学习-设计风活动海报-v2.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/机器学习-设计风活动海报-v3.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/机器学习-设计风活动海报-v4.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/海报-小红书-无二维码.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 灭霸 AI 入门/灭霸-ai入门-活动海报.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 灭霸 AI 入门/机器学习-活动海报-v2.png"
  ],
  "sourceFileMtimes": {
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/公众号推文.html": 1781600286,
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/发布页.html": 1781603245,
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/小红书标题.txt": 1781600286,
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/小红书正文.txt": 1781600286,
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/推文.md": 1781600243,
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/机器学习-活动海报-v3.png": 1781595104,
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/机器学习-设计风活动海报-v1.png": 1781597233,
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/机器学习-设计风活动海报-v2.png": 1781598042,
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/机器学习-设计风活动海报-v3.png": 1781598724,
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/机器学习-设计风活动海报-v4.png": 1781599858,
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 机器学习/海报-小红书-无二维码.png": 1781600285,
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 灭霸 AI 入门/灭霸-ai入门-活动海报.png": 1781593772,
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 灭霸 AI 入门/机器学习-活动海报-v2.png": 1781594026
  },
  "extractedFields": {
    "title": "机器学习：从底层逻辑更好地学习和理解 AI",
    "startAt": "2026-06-17T19:00:00+07:00",
    "endAt": "2026-06-17T21:00:00+07:00",
    "venueName": "清迈客栈",
    "priceLabel": "免费参与",
    "registrationLabel": "CMI Map 一键报名",
    "hostName": "爱德蒙的东风破 × CMI 社区",
    "language": "中文",
    "suitableFor": [
      "AI 工具使用者",
      "机器学习初学者",
      "Codex / Agent 学习者",
      "想线下学习讨论的人"
    ],
    "summary": "从吴恩达《机器学习》课程开始，理解 AI 背后的基本逻辑、能力边界和学习路径。"
  },
  "assetSource": "official_poster",
  "posterUrl": "/cmi-home/event-posters/cmi-machine-learning-intro-2026-06-17.png",
  "cardBackgroundUrl": "/cmi-home/event-card-backgrounds/cmi-machine-learning-intro-2026-06-17.jpg",
  "storagePosterUrl": "https://sfpcpxlxslnulzlmjcby.supabase.co/storage/v1/object/public/cmi-event-posters/posters/cmi-machine-learning-intro-2026-06-17-1781682307571.png",
  "syncRunAt": "2026-06-17T14:48:58+07:00",
  "publicScopePolicy": "cmi_inn_and_cmi_community_only",
  "publishedVia": "pnpm cmi:event:publish --admin-publish",
  "detailBodySource": "official_markdown_or_wechat_manual",
  "mergedDuplicateMaterial": [
    "/Users/andreas/CMI/活动宣传内容/六月活动/0617 灭霸 AI 入门"
  ]
}'::jsonb
),
(
  'cmi-wild-chiang-mai-nature-quest-2026-06-18',
  '清迈神奇动物在哪里｜雨季自然探索任务',
  'cmi',
  '2026-06-18T16:30:00+07:00',
  '2026-06-30T23:59:00+07:00',
  null,
  null,
  '清迈客栈',
  'CMI / 清迈客栈',
  18.7932,
  98.9874,
  '外出门票与交通费用如有，以现场实际为准',
  'CMI Map 一键报名',
  'cmi',
  'CMI 活动宣传内容文件夹',
  null,
  'CMI 社区',
  '中文',
  array['清迈自然观察', '散步拍照', '动植物爱好者', '想用 CMI Map 参与主题任务的人'],
  true,
  true,
  'verified',
  'published',
  '2026-06-17T14:48:58+07:00',
  '2026-06-18T14:30:00+07:00',
  '信息来自 6月18日 清迈神奇动物在哪里 wechat-manual.md、图片序列和小红书最终封面；线下集合时间、目的地、线上参与方式、费用说明和 CMI 归属均明确。',
  array['CMI', '清迈客栈', 'CMI Map', '自然探索', '动植物', '主题活动'],
  '6 月 18 日至 6 月 30 日，CMI 发起“清迈神奇动物在哪里”主题活动，包含两次线下自然探索和线上赏金猎人任务。',
  'CMI 社区',
  'events@cmimap.com',
  null,
  null,
  true,
  'open',
  'count-only',
  'https://sfpcpxlxslnulzlmjcby.supabase.co/storage/v1/object/public/cmi-event-posters/posters/cmi-wild-chiang-mai-nature-quest-2026-06-18-1781682310940.jpg',
  '清迈的雨季，不只是阵雨和潮湿。山林开始变得更绿，昆虫、鸟类、植物和动物也在这个季节变得更容易被看见。

6 月 18 日到 6 月 30 日，CMI 会发起「清迈神奇动物在哪里」主题活动。线下有两次自然探索，线上会同步开启「寻找神奇动物赏金猎人」挑战。

线下第一期「探寻」：2026 年 6 月 18 日（周四）16:30 清迈客栈集合，17:00-21:00 进入清迈夜间动物园探索。

线下第二期「感受」：2026 年 6 月 25 日（周四）12:30 清迈客栈集合，13:00-15:30 在素贴山-蒲屏公园观察植物、鸟类、昆虫和动物。

线上活动：2026 年 6 月 18 日至 6 月 30 日，在小红书分享你在清迈找到的神奇动植物，带话题 #cmi社区 #清迈神奇动物在哪里，并 @清迈客栈CMI社区，即可参与线上活动。奖品为 3D 打印绿尾太阳鸟模型。

活动地点：清迈客栈集合；两期目的地分别为清迈夜间动物园、素贴山-蒲屏公园。费用说明：外出门票与交通费用如有，以现场实际为准。通过 CMI Map 一键报名后，确认邮件会附上微信群、联系人二维码和到场指引。',
  '{
  "sourceFiles": [
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cmimap-screenshots-contact-sheet.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-2.35-shenqi-shengwu-900w.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-2.35-shenqi-shengwu.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-work/crop-1.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-work/crop-2.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-work/crop-3.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-work/crop-4.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-work/crop-5.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/image-sequence-v2.md",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/image-sequence.md",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/01-black-cat.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/01-main-kv.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/02-map-route-pins.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/02-orange-civet.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/03-city-wall-gate.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/03-map-route-pins.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/04-city-wall-gate.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/04-cmimap-phone-concept.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/05-blue-monkey-map.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/05-cmimap-phone-concept.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/06-blue-monkey-map.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/06-cmi-community-logo.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/07-cmi-community-logo.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/07-lingke-wechat-qr.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/08-lingke-wechat-qr.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/01-main-kv.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/02-cmimap-home-entry.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/03-cmimap-activity-page.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/04-cmimap-ranking.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/05-cmimap-captures-feed.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/06-cmimap-camera-capture.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/07-cmimap-ai-result.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/08-cmimap-profile-records.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/09-city-wall-gate.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/10-cmi-community-logo.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/11-lingke-wechat-qr.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/01-main-kv.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/02-cmimap-home-entry.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/03-cmimap-activity-page.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/04-cmimap-ranking.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/05-cmimap-captures-feed.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/06-cmimap-camera-capture.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/07-cmimap-ai-result.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/08-cmimap-profile-records.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/09-city-wall-gate.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/10-cmi-community-logo.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/11-lingke-wechat-qr.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/01-main-kv.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/02-cmimap-phone-concept.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/03-black-cat.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/04-orange-civet.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/05-blue-monkey-map.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/06-city-wall-gate.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/07-map-route-pins.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/raw-cmimap-event.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/raw-cmimap-guide.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/raw-cmimap-home.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/01-title-wordmark.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/02-orange-civet.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/03-black-cat.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/04-blue-monkey-map.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/05-pink-elephant.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/06-subtitle-strip.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/07-gecko.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/08-red-hornbill.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/09-red-lantern.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/10-butterfly.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/11-red-fish.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/12-pink-lantern.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/13-cmi-map-phone.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/14-temple.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/15-city-wall-gate.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/16-map-route-pins.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/17-concept-phone-preview.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/18-concept-main-article-strip.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/19-concept-map-article-strip.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/20-cmimap-phone-product-concept.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/asset-contact-sheet.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/assets-readme.md",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/source-generated-sticker-sheet.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/sticker-sheet-transparent.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy-editable-source.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy-local-images.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy-lossless.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy-v2-publish-local.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy-v2-publish.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy-v2.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-layout-concept-kv-card-style.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-layout-concept-v2.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/01-header.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/02-intro.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/03-how-to-play.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/04-offline-exploration.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/05-bounty-task.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/06-online-participation.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/07-cmimap.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/08-who-should-join.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/09-event-info.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/10-cmi-community-card.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices.md",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-manual-v2.md",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-manual.md",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-after-cmimap.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-all-green.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-beige-top-footer-no-green.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-fresh-long-final.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-fresh-long.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-green-beige-restored.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-green-kv-final.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-hybrid-copy.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-info-clear.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-kv-layout.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-lossless-copy.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-reference-style.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-top-white.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-v2-aligned.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-v2-publish-footer.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-v2-publish-map.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-v2-publish-top.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-v2-publish.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-v2.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-with-cmi-card.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-cards.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/01-cover-kv.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/02-intro-offline.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/03-map-step-01.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/04-map-step-02.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/05-map-step-03.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/06-map-step-04.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/07-map-step-05.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/08-map-step-06.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/09-map-step-07.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/10-how-to-join.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/11-cmi-community-card.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-contact-sheet.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/01-cover-kv.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/02-title-intro.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/03-offline-plan.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/04-map-step-01.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/05-map-step-02.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/06-map-step-03.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/07-map-step-04.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/08-map-step-05.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/09-map-step-06.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/10-map-step-07.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/11-how-to-join.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/12-cmi-community-card.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final-contact-sheet.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final.md",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images.md",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/01-xiaohongshu-slice.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/02-xiaohongshu-slice.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/03-xiaohongshu-slice.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/04-xiaohongshu-slice.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/05-xiaohongshu-slice.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/06-xiaohongshu-slice.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/07-xiaohongshu-slice.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/08-xiaohongshu-slice.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices-contact-sheet.jpg",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices.md"
  ],
  "sourceFileMtimes": {
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cmimap-screenshots-contact-sheet.jpg": 1781588013,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-2.35-shenqi-shengwu-900w.png": 1781577872,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-2.35-shenqi-shengwu.png": 1781577872,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-work/crop-1.png": 1781577677,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-work/crop-2.png": 1781577677,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-work/crop-3.png": 1781577677,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-work/crop-4.png": 1781577677,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/cover-work/crop-5.png": 1781577677,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/image-sequence-v2.md": 1781588458,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/image-sequence.md": 1781541898,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/01-black-cat.png": 1781537675,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/01-main-kv.png": 1781541665,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/02-map-route-pins.png": 1781541665,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/02-orange-civet.png": 1781537675,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/03-city-wall-gate.png": 1781541665,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/03-map-route-pins.png": 1781537675,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/04-city-wall-gate.png": 1781537675,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/04-cmimap-phone-concept.png": 1781541665,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/05-blue-monkey-map.png": 1781541665,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/05-cmimap-phone-concept.png": 1781537675,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/06-blue-monkey-map.png": 1781537675,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/06-cmi-community-logo.png": 1781541665,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/07-cmi-community-logo.png": 1781539580,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/07-lingke-wechat-qr.jpg": 1781541665,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload/08-lingke-wechat-qr.jpg": 1781539548,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/01-main-kv.png": 1781541665,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/02-cmimap-home-entry.png": 1781588107,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/03-cmimap-activity-page.png": 1781588107,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/04-cmimap-ranking.png": 1781588108,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/05-cmimap-captures-feed.png": 1781588108,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/06-cmimap-camera-capture.png": 1781588108,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/07-cmimap-ai-result.png": 1781588108,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/08-cmimap-profile-records.png": 1781588109,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/09-city-wall-gate.png": 1781541665,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/10-cmi-community-logo.png": 1781541665,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2/11-lingke-wechat-qr.jpg": 1781541665,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/01-main-kv.jpg": 1781599020,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/02-cmimap-home-entry.jpg": 1781599020,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/03-cmimap-activity-page.jpg": 1781599020,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/04-cmimap-ranking.jpg": 1781599020,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/05-cmimap-captures-feed.jpg": 1781599020,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/06-cmimap-camera-capture.jpg": 1781599020,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/07-cmimap-ai-result.jpg": 1781599020,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/08-cmimap-profile-records.jpg": 1781599020,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/09-city-wall-gate.jpg": 1781599020,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/10-cmi-community-logo.jpg": 1781599020,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/images-for-upload-v2-publish/11-lingke-wechat-qr.jpg": 1781599020,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/01-main-kv.png": 1781536023,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/02-cmimap-phone-concept.png": 1781536023,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/03-black-cat.png": 1781536130,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/04-orange-civet.png": 1781536130,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/05-blue-monkey-map.png": 1781536130,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/06-city-wall-gate.png": 1781536130,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/previous-upload-assets/07-map-route-pins.png": 1781536130,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/raw-cmimap-event.png": 1781535292,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/raw-cmimap-guide.png": 1781535296,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/source-screenshots/raw-cmimap-home.png": 1781535289,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/01-title-wordmark.png": 1781534927,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/02-orange-civet.png": 1781534927,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/03-black-cat.png": 1781534927,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/04-blue-monkey-map.png": 1781534927,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/05-pink-elephant.png": 1781534927,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/06-subtitle-strip.png": 1781534927,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/07-gecko.png": 1781534927,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/08-red-hornbill.png": 1781534927,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/09-red-lantern.png": 1781534927,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/10-butterfly.png": 1781534927,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/11-red-fish.png": 1781534927,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/12-pink-lantern.png": 1781534927,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/13-cmi-map-phone.png": 1781534927,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/14-temple.png": 1781534928,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/15-city-wall-gate.png": 1781534928,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/16-map-route-pins.png": 1781534928,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/17-concept-phone-preview.png": 1781534848,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/18-concept-main-article-strip.png": 1781534848,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/19-concept-map-article-strip.png": 1781534848,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/20-cmimap-phone-product-concept.png": 1781536130,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/asset-contact-sheet.jpg": 1781534928,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/assets-readme.md": 1781534928,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/source-generated-sticker-sheet.png": 1781534536,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/transparent-assets/sticker-sheet-transparent.png": 1781534797,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy-editable-source.html": 1781541936,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy-local-images.html": 1781541750,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy-lossless.html": 1781541054,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy-v2-publish-local.html": 1781599157,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy-v2-publish.html": 1781599157,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy-v2.html": 1781588980,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-copy.html": 1781599157,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-layout-concept-kv-card-style.png": 1781533527,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-layout-concept-v2.png": 1781532784,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/01-header.png": 1781541053,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/02-intro.png": 1781541053,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/03-how-to-play.png": 1781541053,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/04-offline-exploration.png": 1781541053,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/05-bounty-task.png": 1781541053,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/06-online-participation.png": 1781541053,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/07-cmimap.png": 1781541053,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/08-who-should-join.png": 1781541053,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/09-event-info.png": 1781541053,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices/10-cmi-community-card.png": 1781541053,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-lossless-slices.md": 1781541054,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-manual-v2.md": 1781588414,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-manual.md": 1781541831,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-after-cmimap.png": 1781535625,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-all-green.png": 1781538797,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-beige-top-footer-no-green.png": 1781540537,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-fresh-long-final.png": 1781537896,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-fresh-long.png": 1781537574,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-green-beige-restored.png": 1781539086,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-green-kv-final.png": 1781538408,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-hybrid-copy.png": 1781541978,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-info-clear.png": 1781539267,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-kv-layout.png": 1781536407,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-lossless-copy.png": 1781541089,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-reference-style.png": 1781536857,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-top-white.png": 1781539825,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-v2-aligned.png": 1781589037,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-v2-publish-footer.png": 1781599842,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-v2-publish-map.png": 1781599842,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-v2-publish-top.png": 1781599842,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-v2-publish.png": 1781599502,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-v2.png": 1781588295,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/wechat-preview-with-cmi-card.png": 1781539695,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-cards.html": 1781666229,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/01-cover-kv.jpg": 1781665990,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/02-intro-offline.jpg": 1781665990,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/03-map-step-01.jpg": 1781665990,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/04-map-step-02.jpg": 1781665990,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/05-map-step-03.jpg": 1781665990,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/06-map-step-04.jpg": 1781665990,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/07-map-step-05.jpg": 1781665990,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/08-map-step-06.jpg": 1781665990,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/09-map-step-07.jpg": 1781665990,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/10-how-to-join.jpg": 1781665991,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images/11-cmi-community-card.jpg": 1781665991,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-contact-sheet.jpg": 1781665991,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/01-cover-kv.jpg": 1781666292,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/02-title-intro.jpg": 1781666292,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/03-offline-plan.jpg": 1781666292,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/04-map-step-01.jpg": 1781666292,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/05-map-step-02.jpg": 1781666292,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/06-map-step-03.jpg": 1781666292,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/07-map-step-04.jpg": 1781666292,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/08-map-step-05.jpg": 1781666292,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/09-map-step-06.jpg": 1781666292,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/10-map-step-07.jpg": 1781666292,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/11-how-to-join.jpg": 1781666292,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final/12-cmi-community-card.jpg": 1781666292,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final-contact-sheet.jpg": 1781666293,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images-final.md": 1781666293,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-post-images.md": 1781665991,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/01-xiaohongshu-slice.jpg": 1781665873,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/02-xiaohongshu-slice.jpg": 1781665873,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/03-xiaohongshu-slice.jpg": 1781665873,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/04-xiaohongshu-slice.jpg": 1781665873,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/05-xiaohongshu-slice.jpg": 1781665873,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/06-xiaohongshu-slice.jpg": 1781665873,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/07-xiaohongshu-slice.jpg": 1781665873,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices/08-xiaohongshu-slice.jpg": 1781665873,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices-contact-sheet.jpg": 1781665873,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月18日 清迈神奇动物在哪里/xiaohongshu-slices.md": 1781665873
  },
  "extractedFields": {
    "title": "清迈神奇动物在哪里｜雨季自然探索任务",
    "startAt": "2026-06-18T16:30:00+07:00",
    "endAt": "2026-06-30T23:59:00+07:00",
    "venueName": "清迈客栈",
    "priceLabel": "外出门票与交通费用如有，以现场实际为准",
    "registrationLabel": "CMI Map 一键报名",
    "hostName": "CMI 社区",
    "language": "中文",
    "suitableFor": [
      "清迈自然观察",
      "散步拍照",
      "动植物爱好者",
      "想用 CMI Map 参与主题任务的人"
    ],
    "summary": "6 月 18 日至 6 月 30 日，CMI 发起“清迈神奇动物在哪里”主题活动，包含两次线下自然探索和线上赏金猎人任务。"
  },
  "assetSource": "official_poster",
  "posterUrl": "/cmi-home/event-posters/cmi-wild-chiang-mai-nature-quest-2026-06-18.jpg",
  "cardBackgroundUrl": "/cmi-home/event-card-backgrounds/cmi-wild-chiang-mai-nature-quest-2026-06-18.jpg",
  "storagePosterUrl": "https://sfpcpxlxslnulzlmjcby.supabase.co/storage/v1/object/public/cmi-event-posters/posters/cmi-wild-chiang-mai-nature-quest-2026-06-18-1781682310940.jpg",
  "syncRunAt": "2026-06-17T14:48:58+07:00",
  "publicScopePolicy": "cmi_inn_and_cmi_community_only",
  "publishedVia": "pnpm cmi:event:publish --admin-publish",
  "detailBodySource": "official_markdown_or_wechat_manual"
}'::jsonb
),
(
  'cmi-kongxiang-canteen-zongzi-2026-06-19',
  '空想食堂端午特别版｜跟着紫姀姐一起包粽子',
  'cmi',
  '2026-06-19T16:00:00+07:00',
  null,
  null,
  null,
  '清迈客栈',
  'CMI / 清迈客栈',
  18.7932,
  98.9874,
  '免费参与',
  'CMI Map 一键报名',
  'cmi',
  'CMI 活动宣传内容文件夹',
  null,
  'CMI 社区',
  '中文',
  array['端午节', '社区晚餐', '手作包粽子', '周五下午轻社交'],
  true,
  true,
  'verified',
  'published',
  '2026-06-17T14:48:58+07:00',
  '2026-06-19T14:00:00+07:00',
  '信息来自 6月19日 空想食堂端午包粽子推文、发布页与官方海报；时间、地点、费用和参与方式均明确。',
  array['CMI', '清迈客栈', '空想食堂', '端午', '包粽子', '免费'],
  '端午前的空想食堂特别版，紫姀姐带大家在清迈客栈一起包粽子。',
  'CMI 社区',
  'events@cmimap.com',
  null,
  null,
  true,
  'open',
  'count-only',
  'https://sfpcpxlxslnulzlmjcby.supabase.co/storage/v1/object/public/cmi-event-posters/posters/cmi-kongxiang-canteen-zongzi-2026-06-19-1781682322433.png',
  '每周五，清迈客栈都会有一场「空想食堂」。大家在厨房和客厅里聚在一起，做一点吃的，聊一点生活。

这个周五刚好遇上端午，所以这一次的空想食堂会做成一场端午特别版：一起包粽子。

这次包粽子，紫姀姐会来现场教大家。她和一些社区朋友特意去山上摘了粽叶，准备把这一点熟悉的端午味道带回清迈客栈。

不需要会包粽子，也不需要提前练习。可以洗粽叶、放糯米、包起来、系好，再一起等粽子出锅。

活动信息：2026 年 6 月 19 日（周五）16:00 开始，地点清迈客栈，免费参与。原始参与方式为无需报名、直接空降即可；通过 CMI Map 一键报名后，确认邮件会附上微信群、联系人二维码和到场指引。',
  '{
  "sourceFiles": [
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/公众号推文.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/发布页.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/小红书标题.txt",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/小红书正文.txt",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/推文.md",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/海报-公众号-有二维码.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/海报-小红书-无二维码.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/特别海报.png"
  ],
  "sourceFileMtimes": {
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/公众号推文.html": 1781667364,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/发布页.html": 1781667364,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/小红书标题.txt": 1781667364,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/小红书正文.txt": 1781667364,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/推文.md": 1781667364,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/海报-公众号-有二维码.png": 1781668176,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/海报-小红书-无二维码.png": 1781668209,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6月19日 空想食堂端午包粽子/特别海报.png": 1781668417
  },
  "extractedFields": {
    "title": "空想食堂端午特别版｜跟着紫姀姐一起包粽子",
    "startAt": "2026-06-19T16:00:00+07:00",
    "endAt": null,
    "venueName": "清迈客栈",
    "priceLabel": "免费参与",
    "registrationLabel": "CMI Map 一键报名",
    "hostName": "CMI 社区",
    "language": "中文",
    "suitableFor": [
      "端午节",
      "社区晚餐",
      "手作包粽子",
      "周五下午轻社交"
    ],
    "summary": "端午前的空想食堂特别版，紫姀姐带大家在清迈客栈一起包粽子。"
  },
  "assetSource": "official_poster",
  "posterUrl": "/cmi-home/event-posters/cmi-kongxiang-canteen-zongzi-2026-06-19.png",
  "cardBackgroundUrl": "/cmi-home/event-card-backgrounds/cmi-kongxiang-canteen-zongzi-2026-06-19.jpg",
  "storagePosterUrl": "https://sfpcpxlxslnulzlmjcby.supabase.co/storage/v1/object/public/cmi-event-posters/posters/cmi-kongxiang-canteen-zongzi-2026-06-19-1781682322433.png",
  "syncRunAt": "2026-06-17T14:48:58+07:00",
  "publicScopePolicy": "cmi_inn_and_cmi_community_only",
  "publishedVia": "pnpm cmi:event:publish --admin-publish",
  "detailBodySource": "official_markdown_or_wechat_manual"
}'::jsonb
),
(
  'cmi-ai-open-mic-community-ai-2026-06-19',
  'AI 开放麦第七期｜AI 在社区内的应用',
  'tech',
  '2026-06-19T20:00:00+07:00',
  null,
  null,
  null,
  '清迈客栈',
  'CMI / 清迈客栈',
  18.7932,
  98.9874,
  '免费参与',
  'CMI Map 一键报名',
  'cmi',
  'CMI 活动宣传内容文件夹',
  null,
  'CMI 社区',
  '中文',
  array['AI 工具使用者', '社区建设者', '正在做项目的人', '想听开放讨论的人'],
  true,
  true,
  'verified',
  'published',
  '2026-06-17T14:48:58+07:00',
  '2026-06-19T18:00:00+07:00',
  '信息来自 6.19 AI开放麦第七期推文、发布页与官方海报；时间、地点、费用和参与方式均明确。',
  array['CMI', '清迈客栈', 'AI', '开放麦', '社区', '免费'],
  'AI 开放麦第七期聚焦“AI 在社区内的应用”，讨论 AI 如何帮助真实线下社区记录、连接和协作。',
  'CMI 社区',
  'events@cmimap.com',
  null,
  null,
  true,
  'open',
  'count-only',
  'https://sfpcpxlxslnulzlmjcby.supabase.co/storage/v1/object/public/cmi-event-posters/posters/cmi-ai-open-mic-community-ai-2026-06-19-1781682325238.png',
  '这期 AI 开放麦想聊一个更具体的问题：AI 在社区内的应用。

这里说的社区，不是居民社区，也不是互联网上泛泛的兴趣群，而是像 CMI / 清迈客栈这样，因为话题、活动、共同语境和长期相处聚集起来的线下社区。

这次会聊：AI 能不能帮助一个社区更好地记录自己；能不能让新来的人更快理解这里发生过什么；能不能帮助活动、讨论、项目和人之间产生更好的连接；哪些事情适合 AI 辅助，哪些事情必须继续由人完成。

活动信息：2026 年 6 月 19 日（周五）20:00，空想食堂后；地点清迈客栈；免费参与。原始参与方式为无需报名、直接空降即可；通过 CMI Map 一键报名后，确认邮件会附上微信群、联系人二维码和到场指引。',
  '{
  "sourceFiles": [
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/公众号推文.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/发布页.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/小红书标题.txt",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/小红书正文.txt",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/推文.md",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/海报-小红书-无二维码.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/海报-无二维码.png"
  ],
  "sourceFileMtimes": {
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/公众号推文.html": 1781669043,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/发布页.html": 1781669043,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/小红书标题.txt": 1781668807,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/小红书正文.txt": 1781669043,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/推文.md": 1781669013,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/海报-小红书-无二维码.png": 1781669043,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.19 AI开放麦第七期/海报-无二维码.png": 1781669043
  },
  "extractedFields": {
    "title": "AI 开放麦第七期｜AI 在社区内的应用",
    "startAt": "2026-06-19T20:00:00+07:00",
    "endAt": null,
    "venueName": "清迈客栈",
    "priceLabel": "免费参与",
    "registrationLabel": "CMI Map 一键报名",
    "hostName": "CMI 社区",
    "language": "中文",
    "suitableFor": [
      "AI 工具使用者",
      "社区建设者",
      "正在做项目的人",
      "想听开放讨论的人"
    ],
    "summary": "AI 开放麦第七期聚焦“AI 在社区内的应用”，讨论 AI 如何帮助真实线下社区记录、连接和协作。"
  },
  "assetSource": "official_poster",
  "posterUrl": "/cmi-home/event-posters/cmi-ai-open-mic-community-ai-2026-06-19.png",
  "cardBackgroundUrl": "/cmi-home/event-card-backgrounds/cmi-ai-open-mic-community-ai-2026-06-19.jpg",
  "storagePosterUrl": "https://sfpcpxlxslnulzlmjcby.supabase.co/storage/v1/object/public/cmi-event-posters/posters/cmi-ai-open-mic-community-ai-2026-06-19-1781682325238.png",
  "syncRunAt": "2026-06-17T14:48:58+07:00",
  "publicScopePolicy": "cmi_inn_and_cmi_community_only",
  "publishedVia": "pnpm cmi:event:publish --admin-publish",
  "detailBodySource": "official_markdown_or_wechat_manual"
}'::jsonb
),
(
  'cmi-swap-skills-market-2026-06-20',
  '旧物与技能交换集市',
  'market',
  '2026-06-20T15:00:00+07:00',
  null,
  null,
  null,
  '清迈客栈',
  'CMI / 清迈客栈',
  18.7932,
  98.9874,
  '免费参与',
  'CMI Map 一键报名',
  'cmi',
  'CMI 活动宣传内容文件夹',
  null,
  'CMI 社区',
  '中文',
  array['旧物交换', '技能交换', '新来清迈', '周六下午轻社交'],
  true,
  true,
  'verified',
  'published',
  '2026-06-17T14:48:58+07:00',
  '2026-06-20T13:00:00+07:00',
  '信息来自 6.20 旧物技能交换集市推文、发布页与官方海报；时间、地点、费用和参与方式均明确。原始海报 17MB，本轮压缩为 1280 宽 JPEG 后上传。',
  array['CMI', '清迈客栈', '旧物交换', '技能交换', '市集', '免费'],
  '把闲置旧物和愿意交换的小技能带到清迈客栈，让不用的东西、会做的事重新流动。',
  'CMI 社区',
  'events@cmimap.com',
  null,
  null,
  true,
  'open',
  'count-only',
  'https://sfpcpxlxslnulzlmjcby.supabase.co/storage/v1/object/public/cmi-event-posters/posters/cmi-swap-skills-market-2026-06-20-1781682481763.jpg',
  '我们身边总有一些东西，放着放着就变成了“以后再说”。一本看完很久的书，一件买来没怎么穿的衣服，一个多出来的插头，或者一门别人刚好需要的技能。

这周六，清迈客栈发起一场「旧物与技能交换集市」。这不是正式摊位市集，也不是商业买卖活动，更像是把大家手里闲置的东西、会做的事、愿意交换的时间放到同一张桌子上。

你可以带旧物来换：书、衣服、生活用品、小工具、旅行装备、电子配件、手作物。也可以带技能来换：修图、剪辑、摄影、做饭、语言练习、编程、简历修改、作品集建议、泰国生活经验。

玩法：带一件旧物或一个愿意交换的技能；现场写简单标签；每个人简单介绍自己带来的东西；自由交换、自由聊天。

活动信息：2026 年 6 月 20 日（周六）15:00，地点清迈客栈，免费参与。原始参与方式为无需报名、直接空降即可；通过 CMI Map 一键报名后，确认邮件会附上微信群、联系人二维码和到场指引。',
  '{
  "sourceFiles": [
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/公众号推文.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/发布页.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/小红书标题.txt",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/小红书正文.txt",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/推文.md",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/旧物交换海报无二维码.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/旧物交换海报有二维码.png"
  ],
  "sourceFileMtimes": {
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/公众号推文.html": 1781600222,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/发布页.html": 1781600222,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/小红书标题.txt": 1781600222,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/小红书正文.txt": 1781600222,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/推文.md": 1781600212,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/旧物交换海报无二维码.png": 1781600043,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20旧物技能交换集市！/旧物交换海报有二维码.png": 1781600012
  },
  "extractedFields": {
    "title": "旧物与技能交换集市",
    "startAt": "2026-06-20T15:00:00+07:00",
    "endAt": null,
    "venueName": "清迈客栈",
    "priceLabel": "免费参与",
    "registrationLabel": "CMI Map 一键报名",
    "hostName": "CMI 社区",
    "language": "中文",
    "suitableFor": [
      "旧物交换",
      "技能交换",
      "新来清迈",
      "周六下午轻社交"
    ],
    "summary": "把闲置旧物和愿意交换的小技能带到清迈客栈，让不用的东西、会做的事重新流动。"
  },
  "assetSource": "official_poster",
  "posterUrl": "/cmi-home/event-posters/cmi-swap-skills-market-2026-06-20.jpg",
  "cardBackgroundUrl": "/cmi-home/event-card-backgrounds/cmi-swap-skills-market-2026-06-20.jpg",
  "storagePosterUrl": "https://sfpcpxlxslnulzlmjcby.supabase.co/storage/v1/object/public/cmi-event-posters/posters/cmi-swap-skills-market-2026-06-20-1781682481763.jpg",
  "syncRunAt": "2026-06-17T14:48:58+07:00",
  "publicScopePolicy": "cmi_inn_and_cmi_community_only",
  "publishedVia": "pnpm cmi:event:publish --admin-publish",
  "detailBodySource": "official_markdown_or_wechat_manual",
  "assetProcessing": "official poster compressed to 1280px wide JPEG before Storage upload"
}'::jsonb
),
(
  'cmi-fantastic-fungi-screening-2026-06-20',
  'Magic Lab 观影会｜《神奇蘑菇》',
  'cmi',
  '2026-06-20T19:00:00+07:00',
  null,
  null,
  null,
  '清迈客栈',
  'CMI / 清迈客栈',
  18.7932,
  98.9874,
  '免费参与',
  'CMI Map 一键报名',
  'cmi',
  'CMI 活动宣传内容文件夹',
  null,
  'Magic Lab × CMI',
  '中文',
  array['纪录片观影', '自然生态', '意识与连接主题', '周六晚上'],
  true,
  true,
  'verified',
  'published',
  '2026-06-17T14:48:58+07:00',
  '2026-06-20T17:00:00+07:00',
  '信息来自 6.20 Magic Lab 观影会推文、发布页与官方海报；时间、地点、费用和参与方式均明确。',
  array['CMI', '清迈客栈', 'Magic Lab', '观影会', '纪录片', '免费'],
  'Magic Lab 周六观影会放映《神奇蘑菇》，一起聊森林、菌丝、意识与连接。',
  'Magic Lab × CMI',
  'events@cmimap.com',
  null,
  null,
  true,
  'open',
  'count-only',
  'https://sfpcpxlxslnulzlmjcby.supabase.co/storage/v1/object/public/cmi-event-posters/posters/cmi-fantastic-fungi-screening-2026-06-20-1781682495600.png',
  '在森林脚下，还有一张更古老、更安静的网络。它连接树木，分解死亡，孕育新生。

本周六晚，Magic Lab 观影会一起看《神奇蘑菇》（Fantastic Fungi）。这不是一部只讲蘑菇的自然纪录片，更像一次进入地下世界的旅行。

如果树木之间真的会互相传递信息，如果死亡并不是终点，而是另一种新生的开始，我们该如何重新理解“生命”这件事？

适合喜欢纪录片、自然、生态与生命科学的人；对意识、连接、非人类智慧这些主题有兴趣的人；想在周六晚上安静看一部电影、再和大家聊聊的人。

活动信息：2026 年 6 月 20 日（周六）19:00，地点清迈客栈，免费参与。原始参与方式为不限人数、无需报名、直接空降即可；通过 CMI Map 一键报名后，确认邮件会附上微信群、联系人二维码和到场指引。',
  '{
  "sourceFiles": [
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/公众号推文.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/发布页.html",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/小红书标题.txt",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/小红书正文.txt",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/推文.md",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/海报无二维码.png",
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/海报有二维码.png"
  ],
  "sourceFileMtimes": {
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/公众号推文.html": 1781681498,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/发布页.html": 1781681498,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/小红书标题.txt": 1781681498,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/小红书正文.txt": 1781681498,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/推文.md": 1781680737,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/海报无二维码.png": 1781681452,
    "/Users/andreas/CMI/活动宣传内容/六月活动/6.20 magiclab 观影会——神奇蘑菇/海报有二维码.png": 1781681441
  },
  "extractedFields": {
    "title": "Magic Lab 观影会｜《神奇蘑菇》",
    "startAt": "2026-06-20T19:00:00+07:00",
    "endAt": null,
    "venueName": "清迈客栈",
    "priceLabel": "免费参与",
    "registrationLabel": "CMI Map 一键报名",
    "hostName": "Magic Lab × CMI",
    "language": "中文",
    "suitableFor": [
      "纪录片观影",
      "自然生态",
      "意识与连接主题",
      "周六晚上"
    ],
    "summary": "Magic Lab 周六观影会放映《神奇蘑菇》，一起聊森林、菌丝、意识与连接。"
  },
  "assetSource": "official_poster",
  "posterUrl": "/cmi-home/event-posters/cmi-fantastic-fungi-screening-2026-06-20.png",
  "cardBackgroundUrl": "/cmi-home/event-card-backgrounds/cmi-fantastic-fungi-screening-2026-06-20.jpg",
  "storagePosterUrl": "https://sfpcpxlxslnulzlmjcby.supabase.co/storage/v1/object/public/cmi-event-posters/posters/cmi-fantastic-fungi-screening-2026-06-20-1781682495600.png",
  "syncRunAt": "2026-06-17T14:48:58+07:00",
  "publicScopePolicy": "cmi_inn_and_cmi_community_only",
  "publishedVia": "pnpm cmi:event:publish --admin-publish",
  "detailBodySource": "official_markdown_or_wechat_manual"
}'::jsonb
)
on conflict (id) do update set
  title = excluded.title,
  event_type = excluded.event_type,
  start_at = excluded.start_at,
  end_at = excluded.end_at,
  recurrence = excluded.recurrence,
  stable_schedule = excluded.stable_schedule,
  venue_name = excluded.venue_name,
  area = excluded.area,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  price_label = excluded.price_label,
  registration_label = excluded.registration_label,
  source_type = excluded.source_type,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  host_name = excluded.host_name,
  language = excluded.language,
  suitable_for = excluded.suitable_for,
  is_cmi_related = excluded.is_cmi_related,
  is_verified = excluded.is_verified,
  verification_status = excluded.verification_status,
  visibility_status = excluded.visibility_status,
  last_checked_at = excluded.last_checked_at,
  next_check_before = excluded.next_check_before,
  reliability_note = excluded.reliability_note,
  tags = excluded.tags,
  summary = excluded.summary,
  organizer_name = excluded.organizer_name,
  organizer_email = excluded.organizer_email,
  contact_email = excluded.contact_email,
  capacity = excluded.capacity,
  registration_enabled = excluded.registration_enabled,
  registration_status = excluded.registration_status,
  attendee_visibility = excluded.attendee_visibility,
  cover_image_url = excluded.cover_image_url,
  detail_body = excluded.detail_body,
  raw_source_payload = excluded.raw_source_payload,
  updated_at = timezone('utc'::text, now());
