insert into public.cmi_events (
  id,
  title,
  event_type,
  start_at,
  end_at,
  recurrence,
  stable_schedule,
  venue_name,
  area,
  latitude,
  longitude,
  price_label,
  registration_label,
  source_type,
  source_label,
  source_url,
  host_name,
  language,
  suitable_for,
  is_cmi_related,
  is_verified,
  verification_status,
  visibility_status,
  last_checked_at,
  next_check_before,
  reliability_note,
  tags,
  summary
)
values (
  'cmi-song-of-the-sea-screening-2026-05-23',
  '清迈客栈周六观影会：《海洋之歌》',
  'cmi',
  '2026-05-23T19:30:00+07:00',
  null,
  null,
  null,
  '清迈客栈',
  'CMI / 清迈客栈',
  null,
  null,
  '免费参与',
  '无需报名，直接空降',
  'cmi',
  'CMI 活动宣传内容文件夹',
  null,
  'MagicLab × 清迈客栈',
  '中文',
  array['周六晚上', '电影', '想认识人', '社区活动'],
  true,
  true,
  'verified',
  'published',
  '2026-05-21T11:27:17+07:00',
  '2026-05-23T18:00:00+07:00',
  '信息来自 5.23 观影会海报 OCR 与人工核对；海报明确给出时间、地点、费用和参与方式，未见单独报名链接。',
  array['CMI', '观影会', 'MagicLab', '免费', '周六', '中文友好'],
  'MagicLab 和清迈客栈一起办的周六观影会，放映《海洋之歌》，适合想在社区里轻松认识人的人。'
)
on conflict (id) do update set
  title = excluded.title,
  event_type = excluded.event_type,
  start_at = excluded.start_at,
  end_at = excluded.end_at,
  recurrence = excluded.recurrence,
  stable_schedule = excluded.stable_schedule,
  venue_name = excluded.venue_name,
  area = excluded.area,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  price_label = excluded.price_label,
  registration_label = excluded.registration_label,
  source_type = excluded.source_type,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  host_name = excluded.host_name,
  language = excluded.language,
  suitable_for = excluded.suitable_for,
  is_cmi_related = excluded.is_cmi_related,
  is_verified = excluded.is_verified,
  verification_status = excluded.verification_status,
  visibility_status = excluded.visibility_status,
  last_checked_at = excluded.last_checked_at,
  next_check_before = excluded.next_check_before,
  reliability_note = excluded.reliability_note,
  tags = excluded.tags,
  summary = excluded.summary,
  updated_at = timezone('utc'::text, now());
