insert into public.cmi_events (
  id,
  title,
  event_type,
  start_at,
  end_at,
  recurrence,
  stable_schedule,
  venue_name,
  area,
  latitude,
  longitude,
  price_label,
  registration_label,
  source_type,
  source_label,
  source_url,
  host_name,
  language,
  suitable_for,
  is_cmi_related,
  is_verified,
  verification_status,
  visibility_status,
  last_checked_at,
  next_check_before,
  reliability_note,
  tags,
  summary
)
values (
  'cmi-ai-open-mic-vol-04-2026-05-24',
  'AI 开放麦第四期｜本周 AI 使用现场交流',
  'tech',
  '2026-05-24T19:00:00+07:00',
  null,
  null,
  null,
  '清迈客栈',
  'CMI / 清迈客栈',
  null,
  null,
  '免费参与',
  '无需报名，直接空降即可',
  'cmi',
  'CMI 活动宣传内容文件夹',
  null,
  'CMI 社区',
  '中文',
  array['AI 使用者', '工具实践', '项目交流', '带问题来讨论'],
  true,
  true,
  'verified',
  'published',
  '2026-05-22T17:22:21+07:00',
  '2026-05-24T17:00:00+07:00',
  '信息来自 5.24 AI 开放麦 04 推文 Markdown 与海报，时间、地点、费用和参与方式均明确。',
  array['CMI', 'AI开放麦', 'AI', '工具实践', '免费', '周日'],
  '清迈客栈的第四期 AI 开放麦，围绕本周 AI 使用、工具、项目、案例、踩坑和问题做现场交流。'
)
on conflict (id) do update set
  title = excluded.title,
  event_type = excluded.event_type,
  start_at = excluded.start_at,
  end_at = excluded.end_at,
  recurrence = excluded.recurrence,
  stable_schedule = excluded.stable_schedule,
  venue_name = excluded.venue_name,
  area = excluded.area,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  price_label = excluded.price_label,
  registration_label = excluded.registration_label,
  source_type = excluded.source_type,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  host_name = excluded.host_name,
  language = excluded.language,
  suitable_for = excluded.suitable_for,
  is_cmi_related = excluded.is_cmi_related,
  is_verified = excluded.is_verified,
  verification_status = excluded.verification_status,
  visibility_status = excluded.visibility_status,
  last_checked_at = excluded.last_checked_at,
  next_check_before = excluded.next_check_before,
  reliability_note = excluded.reliability_note,
  tags = excluded.tags,
  summary = excluded.summary,
  updated_at = timezone('utc'::text, now());
