insert into public.cmi_events (
  id,
  title,
  event_type,
  start_at,
  end_at,
  recurrence,
  stable_schedule,
  venue_name,
  area,
  latitude,
  longitude,
  price_label,
  registration_label,
  source_type,
  source_label,
  source_url,
  host_name,
  language,
  suitable_for,
  is_cmi_related,
  is_verified,
  verification_status,
  visibility_status,
  last_checked_at,
  next_check_before,
  reliability_note,
  tags,
  summary
)
values (
  'thailand-inventors-day-road-show-2026-05-24',
  'Thailand Inventors’ Day Road Show 2026 清迈站',
  'tech',
  '2026-05-24T09:00:00+07:00',
  '2026-05-25T18:00:00+07:00',
  null,
  '2026-05-24 至 05-25，具体每日时段以报名页/主办方通知为准',
  'Chiang Mai Grandview Hotel',
  'Chang Phueak / Chiang Mai-Lampang Road',
  18.804857,
  98.97007,
  '免费报名',
  'Google 表单报名',
  'government',
  'NRCT 宣传图 / 报名表',
  'https://forms.gle/hVNecNBySYHAdA1K6',
  'National Research Council of Thailand (NRCT)',
  '泰语 / 中文资料',
  array['研究者', '教育工作者', '创业者', '社区项目', '创新观察'],
  false,
  true,
  'verified',
  'published',
  '2026-05-21T10:23:00+07:00',
  '2026-05-24T09:00:00+07:00',
  '用户提供活动文案和 NRCT 宣传图，确认日期、地点、主办方和报名表；公开材料未给出每日具体开放小时，出发前需以报名页或主办方通知为准。',
  array['科技', '展览', '创新', '研究', '教育', '农业科技', 'PM2.5', '周末', '本周末', '具体时段待确认'],
  'NRCT 在清迈举办的泰国发明家日巡回展，集中展示本土研究、北部地方创新和实际应用，覆盖智慧农业、健康、能源、社区文化遗产和空气污染等主题。'
)
on conflict (id) do update set
  title = excluded.title,
  event_type = excluded.event_type,
  start_at = excluded.start_at,
  end_at = excluded.end_at,
  recurrence = excluded.recurrence,
  stable_schedule = excluded.stable_schedule,
  venue_name = excluded.venue_name,
  area = excluded.area,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  price_label = excluded.price_label,
  registration_label = excluded.registration_label,
  source_type = excluded.source_type,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  host_name = excluded.host_name,
  language = excluded.language,
  suitable_for = excluded.suitable_for,
  is_cmi_related = excluded.is_cmi_related,
  is_verified = excluded.is_verified,
  verification_status = excluded.verification_status,
  visibility_status = excluded.visibility_status,
  last_checked_at = excluded.last_checked_at,
  next_check_before = excluded.next_check_before,
  reliability_note = excluded.reliability_note,
  tags = excluded.tags,
  summary = excluded.summary,
  updated_at = timezone('utc'::text, now());
