insert into public.cmi_events (
  id,
  title,
  event_type,
  start_at,
  end_at,
  recurrence,
  stable_schedule,
  venue_name,
  area,
  latitude,
  longitude,
  price_label,
  registration_label,
  source_type,
  source_label,
  source_url,
  host_name,
  language,
  suitable_for,
  is_cmi_related,
  is_verified,
  verification_status,
  visibility_status,
  last_checked_at,
  next_check_before,
  reliability_note,
  tags,
  summary
)
values (
  'cmi-friday-afternoon-yoga-2026-05-22',
  '清迈夏季养心｜心经阴瑜伽 · 肩颈舒缓课',
  'wellness',
  '2026-05-22T17:00:00+07:00',
  '2026-05-22T18:15:00+07:00',
  null,
  null,
  '清迈客栈',
  'CMI / 清迈客栈',
  null,
  null,
  '场地费 350 THB',
  '公众号查看 / 联系客栈确认',
  'cmi',
  'CMI 活动宣传内容文件夹',
  'https://mp.weixin.qq.com/s/E1ChmH2GQkQp0K6D9DZc4A',
  '沙溪 Karen / Yoga in the Park Chiang Mai',
  '中文',
  array['肩颈紧张', '久坐人群', '睡眠不佳', '想放松身心'],
  true,
  true,
  'verified',
  'published',
  '2026-05-21T14:29:36+07:00',
  '2026-05-22T14:00:00+07:00',
  '日期来自活动文件夹名称“5.22”，时间、地点、费用和导师信息来自同目录推文 Markdown；原文未提供单独报名链接或二维码说明。',
  array['CMI', '瑜伽', '身心灵', '肩颈舒缓', '收费活动'],
  '一节结合中医经络理论与阴瑜伽的肩颈舒缓课，适合久坐、肩颈紧张或最近睡眠偏浅的人。'
)
on conflict (id) do update set
  title = excluded.title,
  event_type = excluded.event_type,
  start_at = excluded.start_at,
  end_at = excluded.end_at,
  recurrence = excluded.recurrence,
  stable_schedule = excluded.stable_schedule,
  venue_name = excluded.venue_name,
  area = excluded.area,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  price_label = excluded.price_label,
  registration_label = excluded.registration_label,
  source_type = excluded.source_type,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  host_name = excluded.host_name,
  language = excluded.language,
  suitable_for = excluded.suitable_for,
  is_cmi_related = excluded.is_cmi_related,
  is_verified = excluded.is_verified,
  verification_status = excluded.verification_status,
  visibility_status = excluded.visibility_status,
  last_checked_at = excluded.last_checked_at,
  next_check_before = excluded.next_check_before,
  reliability_note = excluded.reliability_note,
  tags = excluded.tags,
  summary = excluded.summary,
  updated_at = timezone('utc'::text, now());
