insert into public.cmi_events (
  id,
  title,
  event_type,
  start_at,
  end_at,
  recurrence,
  stable_schedule,
  venue_name,
  area,
  latitude,
  longitude,
  price_label,
  registration_label,
  source_type,
  source_label,
  source_url,
  host_name,
  language,
  suitable_for,
  is_cmi_related,
  is_verified,
  verification_status,
  visibility_status,
  last_checked_at,
  next_check_before,
  reliability_note,
  tags,
  summary
)
values (
  'cmi-swap-market-2026-05-24',
  '旧物交换市集',
  'market',
  '2026-05-24T14:00:00+07:00',
  '2026-05-24T17:00:00+07:00',
  null,
  null,
  '清迈客栈',
  'CMI / 清迈客栈',
  null,
  null,
  '免费参与',
  '海报附二维码，可扫码进群了解',
  'cmi',
  'CMI 活动宣传内容文件夹',
  null,
  'CMI 社区',
  '中文',
  array['旧物交换', '技能分享', '才艺展示', '周日下午'],
  true,
  true,
  'verified',
  'published',
  '2026-05-22T13:09:43+07:00',
  '2026-05-24T12:00:00+07:00',
  '信息直接来自 5.24 旧物交换市场海报；海报明确写明周日下午两点到五点、地点为清迈客栈，并附带进群二维码。',
  array['CMI', '旧物交换', '市集', '技能分享', '周末'],
  '把旧物、技能、才艺或一次帮助带到清迈客栈，在周日下午和社区做一场轻松的交换与认识。'
)
on conflict (id) do update set
  title = excluded.title,
  event_type = excluded.event_type,
  start_at = excluded.start_at,
  end_at = excluded.end_at,
  recurrence = excluded.recurrence,
  stable_schedule = excluded.stable_schedule,
  venue_name = excluded.venue_name,
  area = excluded.area,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  price_label = excluded.price_label,
  registration_label = excluded.registration_label,
  source_type = excluded.source_type,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  host_name = excluded.host_name,
  language = excluded.language,
  suitable_for = excluded.suitable_for,
  is_cmi_related = excluded.is_cmi_related,
  is_verified = excluded.is_verified,
  verification_status = excluded.verification_status,
  visibility_status = excluded.visibility_status,
  last_checked_at = excluded.last_checked_at,
  next_check_before = excluded.next_check_before,
  reliability_note = excluded.reliability_note,
  tags = excluded.tags,
  summary = excluded.summary,
  updated_at = timezone('utc'::text, now());
