insert into public.cmi_events (
  id,
  title,
  event_type,
  start_at,
  end_at,
  recurrence,
  stable_schedule,
  venue_name,
  area,
  latitude,
  longitude,
  price_label,
  registration_label,
  source_type,
  source_label,
  source_url,
  host_name,
  language,
  suitable_for,
  is_cmi_related,
  is_verified,
  verification_status,
  visibility_status,
  last_checked_at,
  next_check_before,
  reliability_note,
  tags,
  summary
)
values
  (
    'cmi-mindfulness-hour-2026-05-21',
    '正念一小时｜清迈客栈 CMI 社区',
    'cmi',
    '2026-05-21T19:00:00+07:00',
    '2026-05-21T20:30:00+07:00',
    null,
    null,
    '清迈客栈',
    'CMI / 清迈客栈',
    null,
    null,
    '免费参与',
    '无需报名，直接空降即可',
    'cmi',
    'CMI 活动宣传内容文件夹',
    'https://mp.weixin.qq.com/s/xfYyjVtLe9yn8rt-S7YCrg',
    'CMI 社区',
    '中文',
    array['正念练习', '冥想', '想慢下来', '社区活动'],
    true,
    true,
    'verified',
    'published',
    '2026-05-21T12:27:50+07:00',
    '2026-05-21T17:00:00+07:00',
    '信息来自推文 Markdown 与海报 OCR 交叉核对，时间、地点、形式和参与方式均明确。',
    array['CMI', '正念', '冥想', '免费', '中文友好'],
    '一场把静坐冥想、引导练习和开放分享放在一起的晚间正念活动，适合最近想慢下来、少一点内耗的人。'
  ),
  (
    'cmi-kongxiang-canteen-2026-05-22',
    '空想食堂｜清迈客栈周五晚餐',
    'cmi',
    '2026-05-22T19:00:00+07:00',
    null,
    null,
    null,
    '清迈客栈',
    'CMI / 清迈客栈',
    null,
    null,
    '请带一道菜来和大家分享',
    '直接空降即可；海报附有加群二维码',
    'cmi',
    'CMI 活动宣传内容文件夹',
    null,
    'CMI 社区',
    '中文',
    array['社区晚餐', '包饺子', '轻社交', '周五晚上'],
    true,
    true,
    'verified',
    'published',
    '2026-05-21T12:27:50+07:00',
    '2026-05-22T17:00:00+07:00',
    '时间信息来自推文中“5 月 22 日（周五）晚 🕖”的明确表述，其余地点、费用和参与方式来自同一份活动文案与海报。',
    array['CMI', '空想食堂', '周五', '社区活动', '晚餐'],
    '清迈客栈的周五空想食堂，大家带菜一起吃饭、包饺子、聊天，饭后还有小型观影活动。'
  ),
  (
    'cmi-friday-afternoon-yoga-2026-05-22',
    '清迈夏季养心｜心经阴瑜伽 · 肩颈舒缓课',
    'wellness',
    '2026-05-22T17:00:00+07:00',
    '2026-05-22T18:15:00+07:00',
    null,
    null,
    '清迈客栈',
    'CMI / 清迈客栈',
    null,
    null,
    '场地费 350 THB',
    '公众号查看 / 联系客栈确认',
    'cmi',
    'CMI 活动宣传内容文件夹',
    'https://mp.weixin.qq.com/s/E1ChmH2GQkQp0K6D9DZc4A',
    '沙溪 Karen / Yoga in the Park Chiang Mai',
    '中文',
    array['肩颈紧张', '久坐人群', '睡眠不佳', '想放松身心'],
    true,
    true,
    'verified',
    'published',
    '2026-05-21T14:29:36+07:00',
    '2026-05-22T14:00:00+07:00',
    '日期来自活动文件夹名称“5.22”，时间、地点、费用和导师信息来自同目录推文 Markdown；原文未提供单独报名链接或二维码说明。',
    array['CMI', '瑜伽', '身心灵', '肩颈舒缓', '收费活动'],
    '一节结合中医经络理论与阴瑜伽的肩颈舒缓课，适合久坐、肩颈紧张或最近睡眠偏浅的人。'
  ),
  (
    'cmi-song-of-the-sea-screening-2026-05-23',
    '清迈客栈周六观影会：《海洋之歌》',
    'cmi',
    '2026-05-23T19:30:00+07:00',
    null,
    null,
    null,
    '清迈客栈',
    'CMI / 清迈客栈',
    null,
    null,
    '免费参与',
    '无需报名，直接空降',
    'cmi',
    'CMI 活动宣传内容文件夹',
    null,
    'MagicLab × 清迈客栈',
    '中文',
    array['周六晚上', '电影', '想认识人', '社区活动'],
    true,
    true,
    'verified',
    'published',
    '2026-05-21T11:27:17+07:00',
    '2026-05-23T18:00:00+07:00',
    '信息来自 5.23 观影会海报 OCR 与人工核对；海报明确给出时间、地点、费用和参与方式，未见单独报名链接。',
    array['CMI', '观影会', 'MagicLab', '免费', '周六', '中文友好'],
    'MagicLab 和清迈客栈一起办的周六观影会，放映《海洋之歌》，适合想在社区里轻松认识人的人。'
  )
on conflict (id) do update set
  title = excluded.title,
  event_type = excluded.event_type,
  start_at = excluded.start_at,
  end_at = excluded.end_at,
  recurrence = excluded.recurrence,
  stable_schedule = excluded.stable_schedule,
  venue_name = excluded.venue_name,
  area = excluded.area,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  price_label = excluded.price_label,
  registration_label = excluded.registration_label,
  source_type = excluded.source_type,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  host_name = excluded.host_name,
  language = excluded.language,
  suitable_for = excluded.suitable_for,
  is_cmi_related = excluded.is_cmi_related,
  is_verified = excluded.is_verified,
  verification_status = excluded.verification_status,
  visibility_status = excluded.visibility_status,
  last_checked_at = excluded.last_checked_at,
  next_check_before = excluded.next_check_before,
  reliability_note = excluded.reliability_note,
  tags = excluded.tags,
  summary = excluded.summary,
  updated_at = timezone('utc'::text, now());
