update public.cmi_events
set
  visibility_status = 'archived',
  last_checked_at = '2026-05-25T10:09:38+07:00',
  next_check_before = null,
  updated_at = timezone('utc'::text, now())
where id in (
  'cmi-ai-nomad-community-2026-05-20',
  'cmi-mindfulness-hour-2026-05-21',
  'cmi-friday-afternoon-yoga-2026-05-22',
  'cmi-kongxiang-canteen-2026-05-22',
  'cmi-song-of-the-sea-screening-2026-05-23',
  'cmi-swap-market-2026-05-24',
  'cmi-ai-open-mic-vol-04-2026-05-24'
)
and is_cmi_related = true
and coalesce(end_at, start_at) < '2026-05-25T10:09:38+07:00';

insert into public.cmi_events (
  id,
  title,
  event_type,
  start_at,
  end_at,
  recurrence,
  stable_schedule,
  venue_name,
  area,
  latitude,
  longitude,
  price_label,
  registration_label,
  source_type,
  source_label,
  source_url,
  host_name,
  language,
  suitable_for,
  is_cmi_related,
  is_verified,
  verification_status,
  visibility_status,
  last_checked_at,
  next_check_before,
  reliability_note,
  tags,
  summary,
  raw_source_payload
)
values (
  'cmi-waytoagi-codex-maker-lab-2026-05-31',
  'WaytoAGI 第24期「AI切磋大会」Codex 轻造物局 · 清迈站',
  'tech',
  '2026-05-31T12:30:00+07:00',
  '2026-05-31T17:00:00+07:00',
  null,
  null,
  '清迈客栈',
  'CMI / 清迈客栈',
  null,
  null,
  '免费参与',
  'Luma 报名',
  'cmi',
  'CMI 活动宣传内容文件夹',
  'https://mp.weixin.qq.com/s/J2VmewGaqC9liepHmUpoiw',
  'WaytoAGI × 清迈客栈',
  '中文',
  array['AI 开发者', 'Codex 初学者', '内容创作者', '想做 AI 小作品的人'],
  true,
  true,
  'verified',
  'published',
  '2026-05-25T10:09:38+07:00',
  '2026-05-31T10:30:00+07:00',
  '信息来自来源说明、公众号推文 Markdown、公众号离线提取和同目录海报；时间、地点、费用、参与方式和报名链接均明确。',
  array['CMI', 'WaytoAGI', 'AI切磋大会', 'Codex', '工作坊', '免费'],
  'WaytoAGI 第24期 AI 切磋大会清迈站，在清迈客栈用 Codex 现场做出可演示的小作品。',
  '{
    "sourceFiles": [
      "/Users/andreas/CMI/活动宣传内容/五月活动/5.31 WaytoAGI Codex轻造物局清迈站/来源说明.md",
      "/Users/andreas/CMI/活动宣传内容/五月活动/5.31 WaytoAGI Codex轻造物局清迈站/公众号推文-可直接复制.md",
      "/Users/andreas/CMI/活动宣传内容/五月活动/5.31 WaytoAGI Codex轻造物局清迈站/推文.md",
      "/Users/andreas/CMI/活动宣传内容/五月活动/5.31 WaytoAGI Codex轻造物局清迈站/公众号原文提取.html",
      "/Users/andreas/CMI/活动宣传内容/五月活动/5.31 WaytoAGI Codex轻造物局清迈站/海报.png"
    ],
    "sourceFileMtimes": {
      "/Users/andreas/CMI/活动宣传内容/五月活动/5.31 WaytoAGI Codex轻造物局清迈站/公众号原文提取.html": 1779677144,
      "/Users/andreas/CMI/活动宣传内容/五月活动/5.31 WaytoAGI Codex轻造物局清迈站/海报.png": 1779677241,
      "/Users/andreas/CMI/活动宣传内容/五月活动/5.31 WaytoAGI Codex轻造物局清迈站/公众号推文-可直接复制.md": 1779677302,
      "/Users/andreas/CMI/活动宣传内容/五月活动/5.31 WaytoAGI Codex轻造物局清迈站/来源说明.md": 1779677302,
      "/Users/andreas/CMI/活动宣传内容/五月活动/5.31 WaytoAGI Codex轻造物局清迈站/推文.md": 1779677324
    },
    "registrationUrl": "https://luma.com/kl2aa0qz",
    "detailUrl": "https://waytoagi.feishu.cn/share/base/form/shrcn77SdbE5LOCwfAMHWXWkYxb",
    "posterUrl": "/cmi-home/event-posters/cmi-waytoagi-codex-maker-lab-2026-05-31.png",
    "cardBackgroundUrl": "/cmi-home/event-card-backgrounds/cmi-waytoagi-codex-maker-lab-2026-05-31.jpg",
    "manualReviewNotes": []
  }'::jsonb
)
on conflict (id) do update set
  title = excluded.title,
  event_type = excluded.event_type,
  start_at = excluded.start_at,
  end_at = excluded.end_at,
  recurrence = excluded.recurrence,
  stable_schedule = excluded.stable_schedule,
  venue_name = excluded.venue_name,
  area = excluded.area,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  price_label = excluded.price_label,
  registration_label = excluded.registration_label,
  source_type = excluded.source_type,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  host_name = excluded.host_name,
  language = excluded.language,
  suitable_for = excluded.suitable_for,
  is_cmi_related = excluded.is_cmi_related,
  is_verified = excluded.is_verified,
  verification_status = excluded.verification_status,
  visibility_status = excluded.visibility_status,
  last_checked_at = excluded.last_checked_at,
  next_check_before = excluded.next_check_before,
  reliability_note = excluded.reliability_note,
  tags = excluded.tags,
  summary = excluded.summary,
  raw_source_payload = excluded.raw_source_payload,
  updated_at = timezone('utc'::text, now());
