update public.cmi_events
set
  visibility_status = 'archived',
  updated_at = timezone('utc'::text, now())
where id = 'cmi-ai-nomad-community-2026-05-20'
  and end_at < now();

insert into public.cmi_events (
  id,
  title,
  event_type,
  start_at,
  end_at,
  recurrence,
  stable_schedule,
  venue_name,
  area,
  latitude,
  longitude,
  price_label,
  registration_label,
  source_type,
  source_label,
  source_url,
  host_name,
  language,
  suitable_for,
  is_cmi_related,
  is_verified,
  verification_status,
  visibility_status,
  last_checked_at,
  next_check_before,
  reliability_note,
  tags,
  summary
)
values
  (
    'deja-gallery-undo-redo-2026-05-22',
    'UNDO · REDO 艺术展最后一天',
    'exhibition',
    '2026-05-22T08:30:00+07:00',
    '2026-05-22T17:00:00+07:00',
    null,
    '展期至 2026-05-22，周五 08:30-17:00',
    'Déjà Gallery',
    'Wat Ket / Kong Sai Road',
    null,
    null,
    '免费',
    '直接去',
    'venue',
    'Citylife / Time Out 核查',
    'https://www.chiangmaicitylife.com/citynow/whats-on/arts-and-exhibitions/undo-%C2%B7-redo-art-exhibition-at-deja-gallery/',
    'Déjà Gallery',
    '英语 / 泰语',
    array['展览', '下午散步', '艺术空间', '雨天备选'],
    false,
    true,
    'verified',
    'published',
    '2026-05-21T09:56:00+07:00',
    '2026-05-22T11:00:00+07:00',
    'Citylife 核到展期至 5 月 22 日，Time Out 补充当天开放时间；作为最后一天展览推荐，出发前仍建议看场地方动态。',
    array['展览', '免费', '艺术', '本周五', '雨天备选'],
    '一组关于选择、记忆和人生分岔的当代艺术展，5 月 22 日是最后一天，适合想找一个安静文化场景的人。'
  ),
  (
    'maya-pride-cover-dance-forum-2026-05-22',
    'Pride Cover Dance 与平权论坛',
    'festival',
    '2026-05-22T15:30:00+07:00',
    '2026-05-22T20:00:00+07:00',
    null,
    null,
    'MAYA Lifestyle Shopping Center',
    'Nimman / Maya',
    18.8022,
    98.9675,
    '免费',
    '直接去',
    'official',
    'Time Out Pride Guide 核查',
    'https://www.timeout.com/chiang-mai/lgbtq/your-ultimate-guide-to-chiang-mai-pride-2026',
    'Chiang Mai Pride / MAYA',
    '泰语 / 英语',
    array['Pride', '舞蹈', '论坛', '商场顺路'],
    false,
    true,
    'verified',
    'published',
    '2026-05-21T09:56:00+07:00',
    '2026-05-22T12:00:00+07:00',
    'Time Out Pride 专题核到 15:30 开始；结束时间未在公开源明确，按晚间活动估算展示，发布当天建议复核 MAYA/主办方动态。',
    array['Pride', '舞蹈', '论坛', '免费', '本周五'],
    'MAYA 里的 Pride 周五活动，一边是 cover dance 比赛，一边有关于人权、平权与商业责任的论坛。'
  ),
  (
    'carpenter-avenue-intha-dinner-2026-05-22',
    'Intha Dinner 缅甸茵达文化晚餐',
    'meetup',
    '2026-05-22T17:00:00+07:00',
    '2026-05-22T21:00:00+07:00',
    null,
    null,
    'Carpenter Avenue',
    'Chang Phueak / Chotana Road',
    null,
    null,
    '฿1,290',
    '电话预约',
    'venue',
    'Time Out 本周末专题',
    'https://www.timeout.com/chiang-mai/things-to-do/explore-burmese-flavours-at-intha-dinner',
    'Carpenter Avenue',
    '英语 / 泰语',
    array['晚餐', '文化体验', '小众活动', '需要预约'],
    false,
    true,
    'verified',
    'published',
    '2026-05-21T09:56:00+07:00',
    '2026-05-22T12:00:00+07:00',
    'Time Out 核到价格、电话和开始时间；座位和菜单以场地方当天确认为准。',
    array['晚餐', '文化', '缅甸', '需预约', '本周五'],
    'Carpenter Avenue 做的一晚茵达族文化晚餐，有缅甸风味、故事和传统表演，适合想把晚饭变成一次文化体验的人。'
  ),
  (
    'aleenta-wine-pairing-2026-05-22',
    'Aleenta 五道式葡萄酒晚餐',
    'meetup',
    '2026-05-22T18:30:00+07:00',
    '2026-05-22T22:00:00+07:00',
    null,
    null,
    'The 1892 Bar, Aleenta Retreat Chiang Mai',
    'Wat Umong / Suthep',
    null,
    null,
    '฿2,099',
    '电话或 LINE 预约',
    'venue',
    'Citylife 核查',
    'https://www.chiangmaicitylife.com/citynow/whats-on/food-and-drink/wine-pairing-dinner-at-aleenta-retreat-chiang-mai/',
    'Aleenta Retreat Chiang Mai',
    '英语 / 泰语',
    array['晚餐', '葡萄酒', '约会', '需预约'],
    false,
    true,
    'verified',
    'published',
    '2026-05-21T09:56:00+07:00',
    '2026-05-22T12:00:00+07:00',
    'Citylife 核到 20 个座位、价格和预约方式；高价小座位活动，发布当天应提醒用户先订位。',
    array['晚餐', '葡萄酒', '现场音乐', '需预约', '本周五'],
    '一场 20 个座位的小型葡萄酒配餐晚餐，适合想认真吃一顿、听现场音乐、预算更充足的人。'
  ),
  (
    'soul-soak-sense-dhara-dhevi-friday',
    'SOUL SOAK 周五热疗与声音疗愈',
    'wellness',
    null,
    null,
    '{"weekdays":[5],"startTime":"11:00","endTime":"22:00","label":"每周五 11:00-22:00"}'::jsonb,
    '每周五 11:00-22:00，2026-08-31 前',
    'Sense Dhara Dhevi Wellness Club',
    'Dhara Dhevi / Tha Sala',
    null,
    null,
    '฿600',
    '直接去 / 先看场地方',
    'venue',
    'Citylife 核查',
    'https://www.chiangmaicitylife.com/citynow/whats-on/live-music/soul-soak-is-coming-back-every-friday-at-sense-dhara-dhevi-wellness-club/',
    'Sense Dhara Dhevi Chiang Mai',
    '泰语 / 英语',
    array['周五放松', '身心灵', '热疗', '声音疗愈'],
    false,
    true,
    'stable-recurring',
    'published',
    '2026-05-21T09:56:00+07:00',
    '2026-05-22T10:00:00+07:00',
    'Citylife 核到每周五持续到 8 月底；包含热疗、sound healing、DJ 和 Yam Khang 演示，具体环节以场地方当天安排为准。',
    array['身心灵', '周五', '热疗', '音乐', '放松'],
    '一个偏放松和疗愈的周五去处，把热疗、声音疗愈、DJ 和兰纳火足按摩演示放在同一个晚间体验里。'
  ),
  (
    'do-place-opening-2026-05-22',
    'Do Place 开幕夜',
    'meetup',
    '2026-05-22T16:00:00+07:00',
    '2026-05-22T23:00:00+07:00',
    null,
    null,
    'Do Place at The Goodcery',
    'The Goodcery',
    null,
    null,
    '免费',
    '直接去',
    'venue',
    'Time Out 本周末专题',
    'https://www.timeout.com/chiang-mai/things-to-do/weekly-event',
    'Do Place / Tempo.wav',
    '英语 / 泰语',
    array['创意空间', '音乐', '开幕', '认识人'],
    false,
    true,
    'verified',
    'published',
    '2026-05-21T09:56:00+07:00',
    '2026-05-22T12:00:00+07:00',
    'Time Out 核到 5 月 22 日 16:00 开幕；具体演出顺序和结束时间以场地方当晚动态为准。',
    array['开幕', '音乐', '创意空间', '免费', '本周五'],
    '一个新创意空间的开幕夜，有 pop-up radio、DJ、艺术、食物和小型放映，适合想看看清迈新场景的人。'
  ),
  (
    'bboy-jammy-james-breaking-class-2026-05-23',
    'Bboy Jammy James 入门 Breaking 课',
    'sport',
    '2026-05-23T17:00:00+07:00',
    '2026-05-23T18:00:00+07:00',
    null,
    null,
    'Chontana Mall',
    'Chang Phueak',
    null,
    null,
    '免费',
    '扫码报名',
    'venue',
    'Time Out 本周末专题',
    'https://www.timeout.com/chiang-mai/things-to-do/learn-the-breaking-basics-with-bboy-jammy-james',
    'Breaking Chiang Mai',
    '英语 / 泰语',
    array['零基础', '运动', '舞蹈', '周六下午'],
    false,
    true,
    'verified',
    'published',
    '2026-05-21T09:56:00+07:00',
    '2026-05-23T12:00:00+07:00',
    'Time Out 核到免费、地点和 17:00-18:00；名额可能有限，建议提前通过来源页报名。',
    array['运动', '舞蹈', '免费', '零基础', '本周六'],
    '一小时的零基础 breaking 入门课，低门槛、免费，适合周六想动一动又不想报长期课的人。'
  ),
  (
    'northern-scooter-show-2026',
    'Northern Scooter Show 2026',
    'festival',
    '2026-05-23T12:00:00+07:00',
    '2026-05-24T21:00:00+07:00',
    null,
    '2026-05-23 至 05-24 12:00-21:00',
    'Chiangmai Hall, Central Chiangmai Airport',
    'Central Chiangmai Airport',
    18.7695,
    98.9758,
    '฿100',
    '现场购票',
    'venue',
    'Citylife / Time Out 核查',
    'https://www.chiangmaicitylife.com/citynow/whats-on/clubs-and-societies/northern-scooter-show-2026-2/',
    'Go To Scooter BKK / Northern Scooter CNX',
    '泰语 / 英语',
    array['周末', '机车', '展会', 'Central Airport'],
    false,
    true,
    'verified',
    'published',
    '2026-05-21T09:56:00+07:00',
    '2026-05-23T10:00:00+07:00',
    'Citylife 核到 5 月 23-24 日、地点、票价和主要内容；Time Out 补充 12:00-21:00 开放时间。',
    array['周末', '展会', '机车', 'Central Airport', '本周末'],
    '北部大型小轮径 scooter 展，有 500 多台稀有车、配件摊位、DJ/乐队和 Dyno Test Racing，适合机车爱好者或周末想看热闹的人。'
  ),
  (
    'som-tum-rave-828-alleyway-2026-05-23',
    '828 Alleyway Som Tum Rave',
    'music',
    '2026-05-23T19:00:00+07:00',
    '2026-05-23T23:59:00+07:00',
    null,
    null,
    '828.Alleyway',
    'Tha Phae / Chang Klan',
    null,
    null,
    '฿499',
    '直接去 / 看场地方',
    'venue',
    'Time Out 本周末专题',
    'https://www.timeout.com/chiang-mai/things-to-do/turn-up-the-heat-at-828-alleyways-som-tum-rave',
    '828.Alleyway',
    '泰语 / 英语',
    array['夜生活', '音乐', '泰东北菜', '周六晚上'],
    false,
    true,
    'verified',
    'published',
    '2026-05-21T09:56:00+07:00',
    '2026-05-23T15:00:00+07:00',
    'Time Out 核到价格、地点和 19:00 开始；结束时间未公开，按夜间活动展示到当天午夜。',
    array['音乐', '夜生活', '吃饭', '周六晚上', '本周末'],
    '把 som tum、糯米饭、泰东北菜和 DJ 派对放在一起的周六夜活动，适合想吃点辣的再跳舞的人。'
  ),
  (
    'tipsy-thai-trivia-look-inside-2026-05-23',
    'Tipsy Thai Trivia 泰语知识问答夜',
    'meetup',
    '2026-05-23T21:00:00+07:00',
    '2026-05-23T23:00:00+07:00',
    null,
    null,
    'Look Inside CNX',
    'Chiang Mai',
    null,
    null,
    '฿67',
    '直接去',
    'venue',
    'Time Out 本周末专题',
    'https://www.timeout.com/chiang-mai/things-to-do/weekly-event',
    'Look Inside CNX',
    '英语 / 泰语',
    array['社交', '泰语学习', '酒吧', '周六晚上'],
    false,
    true,
    'verified',
    'published',
    '2026-05-21T09:56:00+07:00',
    '2026-05-23T16:00:00+07:00',
    'Time Out 核到 21:00、价格和包含饮品；适合当作线索源，出发前建议看场地方是否仍有座位。',
    array['社交', '泰语', '酒吧', '周六晚上', '本周末'],
    '面向初学者也能玩的泰语知识问答夜，门票含一杯饮品，适合想轻松认识人和练一点泰语的人。'
  ),
  (
    'chiang-mai-music-journey-9-2026-05-24',
    'Chiang Mai Music Journey 9',
    'music',
    '2026-05-24T15:30:00+07:00',
    '2026-05-24T23:59:00+07:00',
    null,
    null,
    'Chiang Mai PAO Public Park',
    'Chang Phueak / PAO Park',
    18.8232,
    98.9737,
    '免费',
    '需提前登记',
    'official',
    'Time Out 本周末专题',
    'https://www.timeout.com/chiang-mai/things-to-do/catch-your-favourite-thai-artists-at-the-free-chiang-mai-music-journey-9-festival',
    'Chiang Mai Municipality',
    '泰语',
    array['演唱会', '免费', '泰国流行音乐', '周日晚上'],
    false,
    true,
    'verified',
    'published',
    '2026-05-21T09:56:00+07:00',
    '2026-05-24T12:00:00+07:00',
    'Time Out 核到免费、需登记、15:30 到午夜；大型免费音乐节可能满员，建议提醒用户先登记。',
    array['音乐', '免费', '周日晚上', '需登记', '本周末'],
    '一场免费的泰国流行音乐节，阵容包含 Bodyslam、Ink Waruntorn、Nont Tanont、Pixxie 等，适合想赶周日晚间城市大活动的人。'
  )
on conflict (id) do update set
  title = excluded.title,
  event_type = excluded.event_type,
  start_at = excluded.start_at,
  end_at = excluded.end_at,
  recurrence = excluded.recurrence,
  stable_schedule = excluded.stable_schedule,
  venue_name = excluded.venue_name,
  area = excluded.area,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  price_label = excluded.price_label,
  registration_label = excluded.registration_label,
  source_type = excluded.source_type,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  host_name = excluded.host_name,
  language = excluded.language,
  suitable_for = excluded.suitable_for,
  is_cmi_related = excluded.is_cmi_related,
  is_verified = excluded.is_verified,
  verification_status = excluded.verification_status,
  visibility_status = excluded.visibility_status,
  last_checked_at = excluded.last_checked_at,
  next_check_before = excluded.next_check_before,
  reliability_note = excluded.reliability_note,
  tags = excluded.tags,
  summary = excluded.summary,
  updated_at = timezone('utc'::text, now());
